using DocumentManagementSystem.Application.Configuration;
using DocumentManagementSystem.Application.Services.Interfaces;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Net.Http.Json;
using System.Text.Json;

namespace DocumentManagementSystem.Application.Services.Gemini;

public class GeminiAiService : IGenAiService
{
	private readonly HttpClient _httpClient;
	private readonly ILogger<GeminiAiService> _logger;
	private readonly GeminiOptions _options;

	public GeminiAiService(
		HttpClient httpClient,
		IOptions<GeminiOptions> options,
		ILogger<GeminiAiService> logger)
	{
		_httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
		_options = options?.Value ?? throw new ArgumentNullException(nameof(options));
		_logger = logger ?? throw new ArgumentNullException(nameof(logger));

		_httpClient.Timeout = TimeSpan.FromSeconds(_options.TimeoutSeconds);
	}

	public async Task<string> GenerateSummaryAsync(string text, int maxLength = 200, CancellationToken ct = default)
	{
		if (string.IsNullOrWhiteSpace(text))
		{
			_logger.LogWarning("Empty or null text provided for summary generation");
			return string.Empty;
		}

		_logger.LogInformation("Starting AI summary generation for text of length {TextLength} characters, target summary length: {MaxLength}",
			text.Length, maxLength);

		if (text.Length > _options.MaxPromptLength)
		{
			_logger.LogWarning("Input text exceeds maximum prompt length ({MaxLength}). Truncating from {OriginalLength} to {MaxLength} characters",
				_options.MaxPromptLength, text.Length, _options.MaxPromptLength);
			text = text.Substring(0, _options.MaxPromptLength);
		}

		var prompt = $"�Provide a concise summary of the following document text in approximately {maxLength} characters or less. Focus on the main points and key information:\n\n{text}";

		var requestBody = new GeminiRequest
		{
			Contents = new[]
			{
				new Content
				{
					Parts = new[] { new Part { Text = prompt } }
				}
			}
		};

		for (int attempt = 1; attempt <= _options.MaxRetries; attempt++)
		{
			try
			{
				var url = $"{_options.ApiEndpoint}/{_options.Model}:generateContent?key={_options.ApiKey}";

				_logger.LogDebug("Sending request to Gemini API (attempt {Attempt}/{MaxRetries}), model: {Model}",
					attempt, _options.MaxRetries, _options.Model);

				var response = await _httpClient.PostAsJsonAsync(url, requestBody, ct);

				if (!response.IsSuccessStatusCode)
				{
					var errorContent = await response.Content.ReadAsStringAsync(ct);
					_logger.LogWarning("Gemini API returned {StatusCode} on attempt {Attempt}/{MaxRetries}: {Error}",
						response.StatusCode, attempt, _options.MaxRetries, errorContent);

					if (attempt < _options.MaxRetries)
					{
						await DelayWithExponentialBackoffAsync(attempt, ct);
						continue;
					}

					throw new HttpRequestException($"Gemini API failed with status {response.StatusCode} after {_options.MaxRetries} attempts: {errorContent}");
				}

				var geminiResponse = await response.Content.ReadFromJsonAsync<GeminiResponse>(ct);

				if (geminiResponse?.Candidates == null || geminiResponse.Candidates.Length == 0)
				{
					_logger.LogWarning("Gemini API returned no candidates in response");
					throw new InvalidOperationException("No summary candidates generated by Gemini API");
				}

				if (geminiResponse.Candidates[0].Content?.Parts == null || geminiResponse.Candidates[0].Content.Parts.Length == 0)
				{
					_logger.LogWarning("Gemini API returned empty content in first candidate");
					throw new InvalidOperationException("Empty content returned by Gemini API");
				}

				var summary = geminiResponse.Candidates[0].Content.Parts[0].Text?.Trim() ?? string.Empty;

				if (string.IsNullOrWhiteSpace(summary))
				{
					_logger.LogWarning("Gemini API returned empty or whitespace summary");
					throw new InvalidOperationException("Empty summary returned by Gemini API");
				}

				_logger.LogInformation("Successfully generated AI summary: {SummaryLength} characters (original text: {TextLength} characters)",
					summary.Length, text.Length);
				_logger.LogDebug("Generated summary preview: {SummaryPreview}",
					summary.Length > 100 ? summary.Substring(0, 100) + "..." : summary);

				return summary;
			}
			catch (TaskCanceledException ex) when (ex.CancellationToken == ct)
			{
				_logger.LogInformation("Summary generation was cancelled");
				throw new OperationCanceledException("Summary generation was cancelled", ex, ct);
			}
			catch (TaskCanceledException ex)
			{
				_logger.LogError(ex, "Gemini API request timed out on attempt {Attempt}/{MaxRetries}", attempt, _options.MaxRetries);

				if (attempt >= _options.MaxRetries)
				{
					throw new TimeoutException($"Gemini API request timed out after {_options.MaxRetries} attempts", ex);
				}

				await DelayWithExponentialBackoffAsync(attempt, ct);
			}
			catch (HttpRequestException ex)
			{
				_logger.LogError(ex, "HTTP error calling Gemini API on attempt {Attempt}/{MaxRetries}", attempt, _options.MaxRetries);

				if (attempt >= _options.MaxRetries)
				{
					throw new HttpRequestException($"Gemini API request failed after {_options.MaxRetries} attempts", ex);
				}

				await DelayWithExponentialBackoffAsync(attempt, ct);
			}
			catch (JsonException ex)
			{
				_logger.LogError(ex, "Failed to parse Gemini API response on attempt {Attempt}/{MaxRetries}", attempt, _options.MaxRetries);

				if (attempt >= _options.MaxRetries)
				{
					throw new InvalidOperationException("Failed to parse Gemini API response after multiple retries", ex);
				}

				await DelayWithExponentialBackoffAsync(attempt, ct);
			}
			catch (InvalidOperationException ex)
			{
				_logger.LogError(ex, "Invalid response from Gemini API on attempt {Attempt}/{MaxRetries}", attempt, _options.MaxRetries);

				if (attempt >= _options.MaxRetries)
				{
					throw;
				}

				await DelayWithExponentialBackoffAsync(attempt, ct);
			}
			catch (Exception ex)
			{
				_logger.LogError(ex, "Unexpected error calling Gemini API: {Message}", ex.Message);
				throw;
			}
		}

		throw new InvalidOperationException($"Failed to generate summary after {_options.MaxRetries} retry attempts");
	}

	private async Task DelayWithExponentialBackoffAsync(int attempt, CancellationToken ct)
	{
		var delay = TimeSpan.FromSeconds(Math.Pow(2, attempt));
		_logger.LogInformation("Retrying after {Delay} seconds (exponential backoff)...", delay.TotalSeconds);
		await Task.Delay(delay, ct);
	}
}
